# Configuration for testing

# Models to test
models:
  - name: "YOLOv12"
    path: "../yolov12/runs/YOLOv12/weights/best.pt"
    conf_threshold: 0.25

  - name : "YOLO-GFL"
    path: "../yolo-gfl/runs/YOLO-GFL/weights/best.pt"
    conf_threshold: 0.25

images:
  - name: "Test Set"
    path: "../dataset/HOME-FIRE/test/images"

# Output directories
output_dirs:
  videos: "../test/output/videos"
  stats: "../test/output/stats"
  data_test: "../test/output/data_test"